language: rust
rust:
  - 1.0.0
  - beta
  - nightly
sudo: false
install:
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then export FEATURE="gnustep_runtime"; export CC="clang"; export CXX="clang++"; else export FEATURE=""; fi
  - curl -sO https://static.rust-lang.org/dist/rust-$TRAVIS_RUST_VERSION-$TARGET.tar.gz
  - tar xf rust-$TRAVIS_RUST_VERSION-$TARGET.tar.gz
  - rm -rf $HOME/rust/lib/rustlib/$TARGET
  - mv rust-$TRAVIS_RUST_VERSION-$TARGET/rustc/lib/rustlib/$TARGET $HOME/rust/lib/rustlib
  - if [[ "$FEATURE" == *"gnustep_runtime"* ]] then git clone https://github.com/gnustep/libobjc2.git; fi
  - if [[ "$FEATURE" == *"gnustep_runtime"* ]] then mkdir libobjc2/build; pushd libobjc2/build fi
  - if [[ "$FEATURE" == *"gnustep_runtime"* ]] then cmake ../; fi
  - if [[ "$FEATURE" == *"gnustep_runtime"* ]] then make DESTDIR=/usr install; fi
  - if [[ "$FEATURE" == *"gnustep_runtime"* ]] then popd; fi

script:
  - cargo build --features $FEATURE
  - cargo test --features $FEATURE
  - cargo doc --features $FEATURE
env:
notifications:
  email:
    on_success: never
os:
  - linux
  - osx
addons:
  apt:
    packages:
      - clang-3.7
      - cmake
